services:
  postgres:
    image: postgres:16
    container_name: nxtara-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: devoluciones
      POSTGRES_USER: devoluciones_user
      POSTGRES_PASSWORD: devoluciones_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
